.build_template: &build_template
  stage: build
  image: espressif/idf:release-v5.0
  tags:
    - build
  variables:
    # Enable ccache for all build jobs. See configure_ci_environment.sh for more ccache related settings.
    IDF_CCACHE_ENABLE: "1"
    BATCH_BUILD: "1"
    V: "0"
    WARNING_STR: ""

.build_examples_template: &build_examples_template
  <<: *build_template
  artifacts:
    when: always
    paths:
      - "**/build*/size.json"
      - "**/build*/build_log.txt"
      - "**/build*/*.bin"
      # upload to s3 server to save the artifacts size
      - "**/build*/*.map"
      - "**/build*/*.elf"
      - "**/build*/flasher_args.json"
      - "**/build*/flash_project_args"
      - "**/build*/config/sdkconfig.json"
      - "**/build*/bootloader/*.bin"
      - "**/build*/bootloader/*.elf"
      - "**/build*/partition_table/*.bin"
      - size_info.txt
    expire_in: 1 week
  variables:
    IDF_CI_BUILD: "1"
  script:
    - pip install --upgrade idf-component-manager
    - pip install idf_build_apps
    - python -m idf_build_apps build -vv
      -p $EXAMPLE_DIR 
      -t all
      --config "sdkconfig.ci.*="
      --build-dir build_@t_@w
      --build-log build_log.txt
      --size-file size.json
      --check-warnings
      --ignore-warning-str "$WARNING_STR"
      --collect-size-info size_info.txt
      --default-build-targets $IDF_TARGET

build_example_chatgpt_demo_v5.0:
  extends:
    - .build_examples_template
    - .rules:build:example_chatgpt_demo
  image: espressif/idf:release-v5.0
  variables:
    IDF_TARGET: esp32s3
    EXAMPLE_DIR: examples/chatgpt_demo

build_example_chatgpt_demo_latest:
  extends:
    - .build_examples_template
    - .rules:build:example_chatgpt_demo
  image: espressif/idf:latest
  variables:
    IDF_TARGET: esp32s3
    EXAMPLE_DIR: examples/chatgpt_demo

build_example_factory_demo_v5.0:
  extends:
    - .build_examples_template
    - .rules:build:example_factory_demo
  #image: espressif/idf:release-v5.0 don't support release-v5.0 now.
  image: espressif/idf:release-v5.1
  variables:
    IDF_TARGET: esp32s3
    EXAMPLE_DIR: examples/factory_demo

build_example_factory_demo_v5.1:
  extends:
    - .build_examples_template
    - .rules:build:example_factory_demo
  image: espressif/idf:release-v5.1
  variables:
    IDF_TARGET: esp32s3
    EXAMPLE_DIR: examples/factory_demo

build_example_factory_demo_latest:
  extends:
    - .build_examples_template
    - .rules:build:example_factory_demo
  image: espressif/idf:latest
  variables:
    IDF_TARGET: esp32s3
    EXAMPLE_DIR: examples/factory_demo

build_example_image_display_v5.0:
  extends:
    - .build_examples_template
    - .rules:build:example_image_display
  image: espressif/idf:release-v5.0
  variables:
    IDF_TARGET: esp32s3
    EXAMPLE_DIR: examples/image_display

build_example_image_display_v5.1:
  extends:
    - .build_examples_template
    - .rules:build:example_image_display
  image: espressif/idf:release-v5.1
  variables:
    IDF_TARGET: esp32s3
    EXAMPLE_DIR: examples/image_display

build_example_image_display_latest:
  extends:
    - .build_examples_template
    - .rules:build:example_image_display
  image: espressif/idf:latest
  variables:
    IDF_TARGET: esp32s3
    EXAMPLE_DIR: examples/image_display

build_example_lv_demos_v5.0:
  extends:
    - .build_examples_template
    - .rules:build:example_lv_demos
  image: espressif/idf:release-v5.0
  variables:
    IDF_TARGET: esp32s3
    EXAMPLE_DIR: examples/lv_demos

build_example_lv_demos_v5.1:
  extends:
    - .build_examples_template
    - .rules:build:example_lv_demos
  image: espressif/idf:release-v5.1
  variables:
    IDF_TARGET: esp32s3
    EXAMPLE_DIR: examples/lv_demos

build_example_lv_demos_latest:
  extends:
    - .build_examples_template
    - .rules:build:example_lv_demos
  image: espressif/idf:latest
  variables:
    IDF_TARGET: esp32s3
    EXAMPLE_DIR: examples/lv_demos

build_example_mp3_demo_v5.0:
  extends:
    - .build_examples_template
    - .rules:build:example_mp3_demo
  image: espressif/idf:release-v5.0
  variables:
    IDF_TARGET: esp32s3
    EXAMPLE_DIR: examples/mp3_demo

build_example_mp3_demo_v5.1:
  extends:
    - .build_examples_template
    - .rules:build:example_mp3_demo
  image: espressif/idf:release-v5.1
  variables:
    IDF_TARGET: esp32s3
    EXAMPLE_DIR: examples/mp3_demo

build_example_mp3_demo_latest:
  extends:
    - .build_examples_template
    - .rules:build:example_mp3_demo
  image: espressif/idf:latest
  variables:
    IDF_TARGET: esp32s3
    EXAMPLE_DIR: examples/mp3_demo

build_example_usb_headset_v5.0:
  extends:
    - .build_examples_template
    - .rules:build:example_usb_headset
  image: espressif/idf:release-v5.0
  variables:
    IDF_TARGET: esp32s3
    EXAMPLE_DIR: examples/usb_headset

build_example_usb_headset_v5.1:
  extends:
    - .build_examples_template
    - .rules:build:example_usb_headset
  image: espressif/idf:release-v5.1
  variables:
    IDF_TARGET: esp32s3
    EXAMPLE_DIR: examples/usb_headset

build_example_usb_headset_latest:
  extends:
    - .build_examples_template
    - .rules:build:example_usb_headset
  image: espressif/idf:latest
  variables:
    IDF_TARGET: esp32s3
    EXAMPLE_DIR: examples/usb_headset

build_example_watering_demo_v5.0:
  extends:
    - .build_examples_template
    - .rules:build:example_watering_demo
  image: espressif/idf:release-v5.0
  variables:
    IDF_TARGET: esp32s3
    EXAMPLE_DIR: examples/watering_demo

build_example_watering_demo_v5.1:
  extends:
    - .build_examples_template
    - .rules:build:example_watering_demo
  image: espressif/idf:release-v5.1
  variables:
    IDF_TARGET: esp32s3
    EXAMPLE_DIR: examples/watering_demo

build_example_watering_demo_latest:
  extends:
    - .build_examples_template
    - .rules:build:example_watering_demo
  image: espressif/idf:latest
  variables:
    IDF_TARGET: esp32s3
    EXAMPLE_DIR: examples/watering_demo